### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by randomwangran** [horizon-blue/tracing#1]
yet another blog site https://thehorizon.blue/

after click https://thehorizon.blue/
```
无法访问此网站 找不到 thehorizon.blue 的服务器 IP 地址。
尝试运行 Windows 网络诊断。
DNS_PROBE_FINISHED_NXDOMAIN
```

Chrome版本 71.0.3578.98（正式版本） （64 位） on Win7 x64

**Comment by horizon-blue** [comment]
啊，忘记把这个链接删掉了。因为我已经停用了这个系统，所以就没给服务器和域名续费，现在无法访问是正常的。
